# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += imx8ulp-microgea-ofcap2.dtb \
			  imx8mp-icore-starterkit.dtb \
			  imx8mp-icore-1gb-starterkit.dtb \
			  imx8mp-icore-fasteth-starterkit.dtb \
			  imx8mp-icore-ctouch2.dtb \
			  imx8mp-icore-2e-starterkit.dtb \
			  imx8mp-smarcore-multimedia-4k.dtb \
			  imx8mp-smarcore-multimedia-4k-ov5640.dtb \
			  imx8mp-smarcore-multimedia-4k-hdmi.dtb \
			  imx8mp-smarcore-multimedia-4k-lvds.dtb \
			  imx8mp-smarcore-multimedia-4k-pcie.dtb \
			  imx8xd-icore-starterkit.dtb \
			  imx8xd-icore-ctouch2.dtb \
			  imx8xd-icore-ctouch2-yes7.dtb \
			  imx8xq-icore-starterkit.dtb \
			  imx8xq-icore-ctouch2.dtb \
			  imx8xq-icore-ctouch2-yes7.dtb \
			  imx8mm-icore-starterkit.dtb \
			  imx8mm-icore-ksz9021-starterkit.dtb \

