# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += imx8ulp-microgea-ofcap2.dtb \
			  imx8mp-icore.dtb \
			  imx8xd-icore-starterkit.dtb \
			  imx8xq-icore-starterkit.dtb \
			  imx8mm-icore-starterkit.dtb \
			  
