# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += imx8mp-icore.dtb \
			  imx8mp-icore-ctouch2.dtb \
			  imx8mp-icore-ctouch2-amp10.dtb \
			  imx8mp-icore-ctouch2-yes10.dtb \
			  imx8mp-smarcore.dtb \
			  imx8mp-smarcore-pcie.dtb \
			  imx8mp-icore-2e.dtb \
			  imx8mm-icore.dtb

